### ISSUE TITLE
5s is too often

### ISSUE THREAD

**Issue by eNTi** [GNUletik/steam-checker#1]
neat idea, but i'd set the default check time to like a day rather then 5s and make it configurable, but never below like 10 minutes or so. just imagin a few thousand people using this.

**Comment by gnuletik** [comment]
I set the default value to 30 seconds. The user is now able to configure it with `-i` option.
Below 10 minutes seems quite a lot !
Steam servers may be able to support 30seconds right ?
Thanks for your issue :)
